### ISSUE TITLE
[Bug] No MIDI control ports

### ISSUE THREAD

**Issue by zigmhount** [SanderVocke/shoopdaloop#293] opened 2024-03-10 18:27 UTC
When starting shoopdaloop, no MIDI control ports (inputs or outputs) are visible in the Jack patchbay.

v 0.1.0+ad6d8d26, running on Debian with Pipewire, both with deb package and portable executable. The MIDI ports for tracks are visible and can be connected, MIDI input on a track works as expected.

**Comment by SanderVocke** [comment] 2024-03-10 22:29
Thanks for catching that, it should probably be a quick fix because this was working at some point. I've been using the device autoconnect only.

**Comment by SanderVocke** [comment] 2024-03-11 09:08
Thanks, you're right - even the autoconnect was broken. Found the bug, fixing in #297

**Comment by SanderVocke** [comment] 2024-03-11 11:41
Fixed in #297 (control port shows up again), but still need to test this with an actual MIDI device.

**Comment by zigmhount** [comment] 2024-03-11 19:50
Thanks! What's the best way for me to test it? Are the "rolling pre-release" packages updated automatically eventually, or should I build it myself?

**Comment by zigmhount** [comment] 2024-03-12 17:44
Doesn't seem to be working :( 
I do get an input port named "control", but after connecting it to my controller, nothing happens when I press buttons.
Also, auto-connect doesn't work (the regex `.*APC.*` should find "APC MINI MIDI 1"), and I don't get a MIDI output port for the controller's lights feedback.
Note that I'm using Pipewire, but Jack midi should work fine nevertheless I suppose...

Let me know if I can get you any useful logs for debugging. I've just attempted QML debugging with QtCreator, but I've never used it before so I have no idea what to look for from there :sweat_smile:

**Comment by zigmhount** [comment] 2024-03-12 18:43
> Did you realize you have to set your own mappings before anything works?

Huh haha, isn't the default akai_apc_mini_mk1.lua mapping file enough? the LUA script status is Listening, but I haven't looked at the content of that file at all :)

**Comment by SanderVocke** [comment] 2024-03-12 19:52
> > Did you realize you have to set your own mappings before anything works?
> 
> Huh haha, isn't the default akai_apc_mini_mk1.lua mapping file enough? the LUA script status is Listening, but I haven't looked at the content of that file at all :)

Ah, sorry, you're right. That should be enough, I didn't realize you had that device! Stay tuned, I'll hook mine up tonight.

**Comment by SanderVocke** [comment] 2024-03-12 21:27
Well, you are right - there is more broken than I thought, both in the autoconnect and the midi handling. A good reminder for me that I should have added regression tests for these.

I think I'll get around to fixing it later this week.

**Comment by SanderVocke** [comment] 2024-03-14 22:15
Well, I am still battling some bugs in MIDI recording playback, but in the meantime, if you want you can play around with a version that at least has the autoconnect and MIDI control port fixed:

https://github.com/SanderVocke/shoopdaloop/actions/runs/8280082702/artifacts/1325760941 (it is the Linux portable install folder, you can download it if you are logged into Github).

It should work again as "advertised" in the docs. Some points:
- The AKAI mini mk1 should work out-of-the-box if its lua script is enabled (settings -> LUA scripts). The functionality is pretty basic - have a look at the help text (question mark next to the script).
- If you want to play with your own manual MIDI rules, disable the script (set "run" to false) and restart the software first. Otherwise the script may still be active.
- The manual MIDI rules can be quite powerful as they have full access to the script interface - but there are not many default rules to choose from yet.

**Comment by SanderVocke** [comment] 2024-03-20 15:18
Update: I expect to upload new binaries tonight. Apart from fixing this, have been putting quite some work into fixing MIDI recording and playback in general. In particular, loops will be a lot smarter in how they deal with CC/sustain pedal/pitch wheel states and already-active notes at the start of recording.

For example, a note that starts to play before recording starts and ends during recording, will be played at the start of loop playback to approximate the same sound.

**Comment by SanderVocke** [comment] 2024-03-20 19:58
Updated the pre-release binaries. I will close this ticket now since I am quite confident the basic problem (no MIDI control ports / autoconnect) is solved. If you find any more issues with it, please open a new one!

**Closed by SanderVocke** 2024-03-20 19:58 UTC
Labels: bug
